POST http://localhost:5095/gamerecords
Content-Type: application/json

{
  "player1Id": 1,
  "player2Id": 2,
  "startTime": "2023-09-17T10:00:00",
  "endTime": "2023-09-17T11:30:00",
  "winnerId": 1
}