@id=482bf53e-21f9-45cc-a409-35dc1aafcfa6

PUT http://localhost:5095/users/{{id}}
Content-Type: application/json

{
  "name": "Updated Name",
  "password": "updatedpassword456",
  "email": "updatedemail@example.com",
  "gameRecords": []
}